set -g default-shell /bin/zsh
set -g prefix C-SPACE
set -g base-index 1
set -g pane-base-index 1
set -g escape-time 1
set -g mouse on
set -g renumber-windows on
set -g repeat-time 1000
set -g mode-keys vi
set -g history-limit 10000
set -g allow-rename off
set -g detach-on-destroy off

set -g default-terminal "tmux-256color"
set -as terminal-overrides ',*:Tc'

set -g status-style 'bg=#333333 fg=#5eacd3'

bind r source-file ~/.config/tmux/tmux.conf
bind g run-shell "~/.config/scripts/open-github #{pane_current_path}"
bind-key f run-shell "tmux neww ~/.config/scripts/tmux-sessionizer"
bind-key h run-shell "tmux neww ~/.config/scripts/tmux-sessionizer ~/work/bpk"
bind-key j run-shell "tmux neww ~/.config/scripts/tmux-sessionizer ~/work/cu-nex/quickattend-backend"
bind-key k run-shell "tmux neww ~/.config/scripts/tmux-sessionizer ~/HPC"
bind-key l run-shell "tmux neww ~/.config/scripts/tmux-sessionizer ~/Desktop/naxocist-cp"
bind-key \; run-shell "tmux neww ~/.config/scripts/tmux-sessionizer ~/Desktop/tmp"

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c  new-window     -c "#{pane_current_path}"

# Stay in copy mode after copying
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi Enter send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection
bind-key -T copy-mode M-w send-keys -X copy-selection
bind-key -T copy-mode Enter send-keys -X copy-selection-and-cancel
