set -g default-shell /bin/zsh
set -g prefix C-SPACE
set -g base-index 1
set -g pane-base-index 1
set -s escape-time 0
set -g mouse on
set -g renumber-windows on
set -g repeat-time 1000
set -g mode-keys vi
set -g history-limit 10000
set -g allow-rename off
set -g detach-on-destroy off

set -g default-terminal "tmux-256color"
set -as terminal-overrides ',*:Tc'

set -g status-style 'bg=#333333 fg=#5eacd3'

bind r source-file ~/.config/tmux/tmux.conf
bind g run-shell "~/.config/scripts/open-github #{pane_current_path}"

# sessionizer
bind-key -r f run-shell "tmux neww ~/.config/scripts/tmux-sessionizer"

# quick project jumps
bind-key -r H run-shell "tmux neww ~/.config/scripts/tmux-sessionizer ~/work/bpk"
bind-key -r J run-shell "tmux neww ~/.config/scripts/tmux-sessionizer ~/work/cu-nex/quickattend-backend"
bind-key -r K run-shell "tmux neww ~/.config/scripts/tmux-sessionizer ~/HPC"
bind-key -r L run-shell "tmux neww ~/.config/scripts/tmux-sessionizer ~/Desktop/naxocist-cp"
bind-key -r \; run-shell "tmux neww ~/.config/scripts/tmux-sessionizer ~/Desktop/tmp"

# splits open in current path
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c  new-window     -c "#{pane_current_path}"

# vim-like pane navigation
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# vi copy mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
bind -T copy-mode-vi Enter send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection
