#!/bin/bash

dir="$1"
cd "$dir" || exit 1

remote=$(git remote get-url origin)

first_char="${remote:0:1}"

url=$remote

if [[ $first_char == "h" ]]; then
  # HTTPS
  :
elif [[ $first_char == "g" ]]; then
  # SSH
  prefix=${remote%%":"*}
  url="https://github.com/${remote:((${#prefix} + 1))}"
else
  # echo "No github remote 'origin' here"
  exit 0
fi

# echo "${url}"
powershell.exe -c start "${url}"
